
#+ summary: Lists all project partners
#+ endpoint_in_url: False
#+ endpoint: http://query.wikidata.org/sparql
#+ tags:
#+   - Projects
#+ enumerate:
#+   - project

PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?partner ?partnerLabel WHERE {
  { ?_project_iri wdt:P527 ?partner . }
  UNION
  { ?_project_iri wdt:P710 ?partner . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
